name:                top-count
version:             0.1.0.0
github:              "luochen1990/top-count"
license:             Apache-2.0
author:              "LuoChen"
maintainer:          "luochen1990@gmail.com"
copyright:           "2019 LuoChen"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/top-count#readme>

dependencies:
- base >= 4.7 && < 5
- temporary
- pqueue
- containers
- directory
- hspec
- QuickCheck

library:
  source-dirs: src

executables:
  top-count-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - top-count

tests:
  top-count-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - top-count
